spring:
  jpa:
    hibernate:
      ddl-auto: update #update
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    url: jdbc:mariadb://localhost:3306/pns_eis?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver #com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: root
server:
  port: 9090
